#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -l walltime=48:00:00,mem=128GB,jobfs=200GB,ncpus=28
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84+gdata/pw1+scratch/pw1


module load bwa
module load samtools

bwa mem -M -R "@RG\tID:SAMPLE\tSM:SAMPLE_l1\tPL:ILLUMINA" -t 28  /g/data/u86/variantdb/v2.38/conf/human/GRCh38/bwa_index/GRCh38d1_noalt READDIR/SAMPLE_R1.fastq.gz READDIR/SAMPLE_R2.fastq.gz |  samtools sort  -@28 -m 4G -o SAMPLE.bam - 


