#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -l walltime=24:00:00,mem=128GB,jobfs=100GB,ncpus=28
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84

module load samtools
module load java/jdk-8.40


samtools depth -a -d 10000 OUTDIR/SAMPLE_md_realign_recal.bam -b BED > OUTDIR/SAMPLE.depth

samtools view -h --threads 28 -L BED OUTDIR/SAMPLE_md_realign_recal.bam | /g/data/u86/software/bbmap/pileup.sh in=stdin > OUTDIR/SAMPLE.mapstat_panel

samtools view -h --threads 28 OUTDIR/SAMPLE_md_realign_recal.bam | /g/data/u86/software/bbmap/pileup.sh in=stdin > OUTDIR/SAMPLE.mapstat_all

