#!/bin/bash
#PBS -P pq84
#PBS -q normal
#PBS -l walltime=96:00:00,mem=32GB,jobfs=200GB,ncpus=1
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84+gdata/pw1+scratch/pw1


module load java
module load samtools
module load python3-as-python


java -Xms3200m -Xmx30g  -jar /g/data/u86/variantdb/v2.3/ext/bin/picard-tools-2.4.1/picard.jar MarkDuplicates AS=TRUE VALIDATION_STRINGENCY=LENIENT  I=OUTDIR/SAMPLE.bam O=OUTDIR/SAMPLE_md.bam M=OUTDIR/SAMPLE_md.txt TMP_DIR=OUTDIR

samtools index OUTDIR/SAMPLE_md.bam

/g/data/u86/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" BaseRecalibrator -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -I OUTDIR/SAMPLE_md.bam -knownSites /g/data/u86/variantdb/v2.38/conf/human/GRCh38/resources//Homo_sapiens_assembly38.dbsnp138.vcf -knownSites /g/data/u86/variantdb/v2.38/conf/human/GRCh38/resources//Mills_and_1000G_gold_standard.indels.hg38.vcf -O OUTDIR/SAMPLE_md_recal.table 

/g/data/u86/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" ApplyBQSR -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -I OUTDIR/SAMPLE_md.bam --bqsr-recal-file OUTDIR/SAMPLE_md_recal.table -O OUTDIR/SAMPLE_md_recal.bam 

/g/data/u86/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" HaplotypeCaller -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -ERC GVCF -I OUTDIR/SAMPLE_md_recal.bam -O OUTDIR/SAMPLE.g.vcf.gz


