#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -l walltime=48:00:00,mem=16GB,jobfs=200GB,ncpus=1
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84+gdata/pw1+scratch/pw1


module load java/jdk-8.40
module load bwa
module load samtools

bwa mem -M -R "@RG\tID:SAMPLE\tSM:SAMPLE_l1\tPL:ILLUMINA" -t 1  /g/data/u86/variantdb/v2.38/conf/human/GRCh38/bwa_index/GRCh38d1_noalt READDIR/SAMPLE_R1.fastq.gz READDIR/SAMPLE_R2.fastq.gz |  /g/data/u86/variantdb/v2.3/ext/bin/samtools view -u -S - | /g/data/u86/software/bin/novosort --md --kt -c 8 -x 6 -m 10G -t $PBS_JOBFS -i -o OUTDIR/SAMPLE.bam -

java -Xms3200m -Xmx3600m  -jar /g/data/u86/variantdb/v2.3/ext/bin/picard-tools-2.4.1/picard.jar MarkDuplicates AS=TRUE VALIDATION_STRINGENCY=LENIENT  I=OUTDIR/SAMPLE.bam O=OUTDIR/SAMPLE_md.bam M=OUTDIR/SAMPLE_md.txt TMP_DIR=OUTDIR

samtools index OUTDIR/SAMPLE_md.bam

/g/data/pq84/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" BaseRecalibrator -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -I OUTDIR/SAMPLE_md.bam --known-sites /g/data/pq84/software/gatk/gatk_resources/dbsnp_146.hg38.vcf --known-sites /g/data/pq84/software/gatk/gatk_resources/Homo_sapiens_assembly38.known_indels.vcf --known-sites /g/data/pq84/software/gatk/gatk_resources/Mills_and_1000G_gold_standard.indels.hg38.vcf -O OUTDIR/SAMPLE_md_recal.table 

/g/data/pq84/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" ApplyBQSR -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -I OUTDIR/SAMPLE_md.bam --bqsr-recal-file OUTDIR/SAMPLE_md_recal.table -O OUTDIR/SAMPLE_md_recal.bam 

/g/data/pq84/software/gatk-4.2.5.0/gatk --java-options "-Djava.io.tmpdir=OUTDIR -Xms3g -Xmx30g" HaplotypeCaller -R /g/data/u86/variantdb/v2.38/conf/human/GRCh38/fasta/single_file/GRCh38d1_noalt.fa -ERC GVCF -I OUTDIR/SAMPLE_md_recal.bam -O OUTDIR/SAMPLE.g.vcf.gz