#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -l walltime=4:00:00,mem=64GB,jobfs=10GB,ncpus=28
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84


module load samtools

SOFT/STAR/bin/Linux_x86_64_static/STAR --sjdbOverhang SJDB_value --readFilesCommand zcat  --outFilterMultimapNmax 10 --outFilterMismatchNmax 1 --alignIntronMax 1 --alignSJDBoverhangMin 0 --outFilterMultimapScoreRange 0 --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 16  --runThreadN 28 --genomeDir REFDIR/REF/READLENGTHbp --outFileNamePrefix OUTDIR/SAMPLE_ --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --readFilesIn READDIR/SAMPLE_R1_trimmed.fq.gz

samtools index OUTDIR/SAMPLE_Aligned.sortedByCoord.out.bam
