#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -l walltime=4:00:00,mem=64GB,jobfs=10GB,ncpus=28
#PBS -l storage=gdata/u86+scratch/u86+gdata/pq84+scratch/pq84

module load samtools

SOFT/STAR/bin/Linux_x86_64_static/STAR --sjdbOverhang SJDB_value --readFilesCommand zcat --runThreadN 28 --genomeDir SOFT/STAR/REF/READLENGTHbp --outFileNamePrefix OUTDIR/SAMPLE_ --outSAMtype BAM SortedByCoordinate --quantMode GeneCounts --readFilesIn READDIR/SAMPLE_R1.fastq.gz READDIR/SAMPLE_R2.fastq.gz

samtools index OUTDIR/SAMPLE_Aligned.sortedByCoord.out.bam

